### ISSUE TITLE
Your guidance

### ISSUE THREAD

**Issue by MyVanitar** [ScarsFun/lvgl_STM32F103_encoder_rtx5#1]
Hi,

thank you for your project.

I want to replicate this for a test project to show something on the LCD with STM32f103C8. I stuck in the hardware configuration for the LittlevGL.

May I ask you to generally explain how to make a hardware configuration/connection between the library and the LCD? because each LCD is different. one is parallel, one is SPI, one uses a different driver chip such as ILI9325... etc

**Comment by ScarsFun** [comment]
You must write a driver for your display . Basically lvgl need only function for flush buffer to display, but is well explained in library documentation. Overall F103C8 has only 20k of ram. This demo needs 16k ram.
Check https://forum.littlevgl.com is a good place to get more info and ask for
